### ISSUE TITLE
Weapons can still sometimes fall through the floor

### ISSUE THREAD

**Issue by bauxiteDYS** [Rainyan/sourcemod-nt-weapon-rescue#5] opened 2024-12-14 19:47 UTC
To reproduce:  

Spawn in with any (big?) weapons, or `give weapon_ghost` and then crouch, look as straight down as possible and kill bind, the weapon/ghost should fall through the floor still. Sorta simulates getting fragged when looking down (like running away with ghost) - most of the cases of weapons falling though floor seem to be related to dropping them on death.

Tested with:
```
Admin File Reader:1.11.0.6939
Admin Help:1.11.0.6939
Admin Menu:1.11.0.6939
Basic Ban Commands:1.11.0.6939
Basic Chat:1.11.0.6939
Basic Comm Control:1.11.0.6939
Basic Commands:1.11.0.6939
Basic Info Triggers:1.11.0.6939
Basic Votes:1.11.0.6939
Client Preferences:1.11.0.6939
Fun Commands:1.11.0.6939
Fun Votes:1.11.0.6939
Nextmap:1.11.0.6939
Map Nominations:1.11.0.6939
NEOTOKYO° Anti Ghost Cap Deny:1.3.1
NT Anti Ghosthop:3.0.0
Comp Server Validator:5v5-20241213
NEOTOKYO° Weapon Drop Tweaks:0.8.4
NEOTOKYO° Ghost capture event:1.10.1
NT MapChooser:0.1.1
NEOTOKYO OnRoundConcluded Event:0.1.0
NT Weapon Rescue:0.1.3
NT Win Condition:0.0.7
Player Commands:1.11.0.6939
Rock The Vote:1.11.0.6939
Sound Commands:1.11.0.6939
```

**Comment by Rainyan** [comment] 2024-12-15 18:39
Any specific map and setpos/setang coordinates to replicate this? If you're seeing this specifically whilst standing on displacement surfaces, this could be a duplicate of #1 

Also note that this plugin at least in its current form is more concerned with returning OOB weapons back in-bounds, rather than outright preventing weapons from going OOB. Although perhaps a better approach would indeed be to try and prevent this from happening in the first place, possibly by changing the weapon drop coordinates to a higher position(?)

**Comment by Rainyan** [comment] 2024-12-15 18:47
Capturing and preventing this might be worth trying:

https://github.com/alliedmodders/hl2sdk/blob/4c27c1305c5e042ae1f62f6dc6ba7e96fd06e05d/game/server/basecombatcharacter.cpp#L1936-L1941

**Comment by bauxiteDYS** [comment] 2024-12-15 22:08
Sorry, user issue, it works as intended. :S
You can probably delete this.

**Closed as completed** 2024-12-15 22:09 UTC
